[[Required]]
    Name = "Subscription"
    Regex = "^Subscription$"
[[Required]]
    Name = "Tenant"
[[Required]]
    Name = "Region"

[[CreateVars]]
    Name = "Create KubeName"
	Key = "KubeName"
	Value = "kube_{{ .Region }}"

[[CreateVars]]
    Name = "Create MCResc"
	Key = "MCResc"
	Value = "MC_{{ .KubeName }}_{{ .KubeName }}_{{ .Region }}"

[[CreateVars]]
    Name = "Create UserMSI"
	Key = "UserMSI"
	Value = "{{ .Region }}-msi-ua"

[[Seqs]]
	Name = "AzLogin"
	Cmd = "az login --use-device-code"

[[Seqs]]
	Name = "SetAccount"
	Cmd = "az account set -s {{.Subscription}}"

[[Seqs]]
	Name = "CreateGroup"
	Cmd = "az group create --name {{ .KubeName }} --location {{ .Region }}"

[[Seqs]]
	Name = "VnetCreate"
	Cmd = "az network vnet create --name {{ .KubeName }} --resource-group {{ .KubeName }} --subnet-name default --subnet-prefix 10.0.0.0/16"
    ValueKey = "VnetInfo"

[[Seqs]]
    Name = "Write Vnet Info"
    Path = "./vnet.json"
    Value = "{{.VnetInfo}}"

[[Seqs]]
# --assign-identity /subscriptions/{{ .Subscription }}/resourcegroups/{{ .Region }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/westus2-msi-ua
	Name = "CreateCluster"
	Cmd = """
	az aks create
	--name kube_{{.Region}}
	--resource-group {{ .KubeName }}
	--os-sku CBLMariner
	--max-pods 250
	--network-plugin azure
	--vnet-subnet-id /subscriptions/{{ .Subscription }}/resourceGroups/{{ .Region }}/providers/Microsoft.Network/virtualNetworks/{{ .KubeName }}/subnets/default
	--docker-bridge-address 172.17.0.1/16
	--service-cidr 10.2.0.0/24
	--enable-managed-identity
	"""
    ValueKey = "ClusterInfo"

[[Seqs]]
    Name = "Write Cluster Info"
    Path = "./cluster.json"
    Value = "{{.ClusterInfo}}"

[[Seqs]]
	Name = "SystemMSI"
	Cmd = "az aks show -g {{ .KubeName }} -n {{ .KubeName }} --query identity"
	ValueKey = "SystemMSI"

[[Seqs]]
    Name = "Write System MSI Info"
    Path = "./system_msi.json"
    Value = "{{.SystemMSI}}"

[[Seqs]]
	Name = "GetCreds"
	Cmd = "az aks get-credentials --resource-group {{ .KubeName }} --name {{ .KubeName }}"

[[Seqs]]
	Name = "GetMSIID"
	Cmd = "az aks show -g {{ .KubeName }} -n {{ .KubeName }} --query \"identityProfile.kubeletidentity.clientId\" -otsv"
	ValueKey = "MSIID"

[[Seqs]]
    Name = "Write System MSI Info 2"
    Path = "./system_msi2.json"
    Value = "{{.MSIID}}"

[[Seqs]]
	Name = "RoleAssignmentManagedIdentity"
	Cmd = """
    az role assignment create 
    --role "Managed Identity Operator" 
    --assignee {{ .MSIID }} 
    --scope /subscriptions/{{ .Subscription }}/resourcegroups/{{ .MCResc }}
    """

[[Seqs]]
	Name = "RoleAssignmentVirtualMachine"
	Cmd = """
	az role assignment create
	--role "Virtual Machine Contributor"
	--assignee {{.MSIID}}
	--scope /subscriptions/{{.Subscription}}/resourcegroups/{{ .MCResc}}
	"""

[[Seqs]]
	Name = "AADPodDeploy"
	Cmd = "kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml"

[[Seqs]]
	Name = "DeployMicAndAKSExceptions"
	Cmd = "kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml"

[[Seqs]]
	Name = "CreateUserMSI"
	Cmd = "az identity create -g {{ .KubeName }} -n {{ .UserMSI }}"

[[Seqs]]
	Name = "GetUserMSIID"
	Cmd = "az identity show -g {{ .KubeName }} -n {{ .UserMSI }} --query clientId -otsv"
    ValueKey = "UserMSIID"
    RetrySleep = "1m"
    Retries = 5

[[Seqs]]
    Name = "GetUserMSIResc"
    Cmd = "az identity show -g {{ .Region }} -n {{ .UserMSI }} --query id -otsv"
    ValueKey = "UserMSIResc"

[[Seqs]]
	Name = "AssignRoleReader"
	Cmd = """
	az role assignment create
	--role Reader
	--assignee {{.UserMSIID}}
	--scope "/subscriptions/{{ .Subscription }}/resourceGroups/{{ .MCResc }}"
	--query id
	-otsv
	"""

[[Seqs]]
    Name = "Write aadident.yaml"
    Path = "./aadident.yaml"
    Value = """
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
    name: {{ .UserMSI }}
spec:
    type: 0
    resourceID: {{ .UserMSIResc }}
    clientID: {{ .UserMSIID }}
  """

[[Seqs]]
    Name = "Write aadbinding.yaml"
    Path = "./aadbinding.yaml"
    Value = """
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
    name: {{ .UserMSI }}-binding
spec:
    azureIdentity: {{ .UserMSI }}
    selector: {{ .UserMSI }}
    """

[[Seqs]]
    Name = "Apply aadident.yaml"
    Cmd = "kubectl apply -f aadident.yaml"

[[Seqs]]
    Name = "Apply aadbinding.yaml"
	Cmd = "kubectl apply -f aadbinding.yaml"